---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EKS Cluster'
Parameters:
  RoleArn:
    Type: String
    Default: arn:aws:iam::852760950639:role/eksClusterRole-eksClusterRole-1RCVJLAEUHOBQ
    Description: RoleArn

  SecurityGroupIds:
    Type: CommaDelimitedList
    Default: sg-04cdd2b72b3ea27db
    Description: Security Group Ids

  SubnetIds:
    Type: CommaDelimitedList
    Default: subnet-058bc2075a7cb9b9c,subnet-02af8d3b13ba9746b,subnet-01e3c279a3d3c97fb,subnet-07330cdaa41e45f3b
    Description: Subnet Ids

Resources:
  eksCluster:
    Type: 'AWS::EKS::Cluster'
    Properties:
      Name: eks-cluster
      Version: '1.21'
      RoleArn: !Ref RoleArn
      ResourcesVpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref SubnetIds

Outputs:
  Arn:
    Description: The ARN of the cluster
    Value: !GetAtt eksCluster.Arn
  CertificateAuthorityData:
    Description: The certificate-authority-data for your cluster
    Value: !GetAtt eksCluster.CertificateAuthorityData
  Endpoint:
    Description: The endpoint for your Kubernetes API server
    Value: !GetAtt eksCluster.Endpoint
  ClusterSecurityGroupId:
    Description: The cluster security group that was created by Amazon EKS for the cluster. Managed node groups use this security group for control plane to data plane communication
    Value: !GetAtt eksCluster.ClusterSecurityGroupId
  eksCluster:
    Description:  The resource name
    Value: !Ref eksCluster
