apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: eks-demo
    app.kubernetes.io/instance: eks-demo-instance
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kubectl
  name: eks-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-demo
  template:
    metadata:
      labels:
        app: eks-demo
    spec:
      containers:
        - image: 852760950639.dkr.ecr.us-east-1.amazonaws.com/eks-poc:latest
          imagePullPolicy: Always
          name: eks-demo
          ports:
            - containerPort: 3000
